# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('callerId', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(choices=[('+84', 'VN(+84)'), ('+1', 'US(+1)')], max_length=5)),
                ('caller_number', models.CharField(max_length=11)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ac_caller',
                'ordering': ('registered_date',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.IntegerField(choices=[(1, 'Private'), (2, 'Global')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ac_category',
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='Registered_Device',
            fields=[
                ('deviceId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('devicePlatform', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Blackberry', 'Blackberry')], max_length=20)),
                ('installed_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ac_registered_device',
                'ordering': ('installed_date',),
            },
        ),
        migrations.AddField(
            model_name='caller',
            name='category',
            field=models.ManyToManyField(to='api.Category'),
        ),
        migrations.AddField(
            model_name='caller',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Registered_Device'),
        ),
        migrations.AddIndex(
            model_name='caller',
            index=models.Index(fields=['country_code', 'caller_number'], name='caller_index'),
        ),
    ]
