# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caller_categories',
            old_name='report_count',
            new_name='total_report_count',
        ),
        migrations.AddField(
            model_name='caller_categories',
            name='negative_sentiment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caller_categories',
            name='positive_sentiment_count',
            field=models.IntegerField(default=0),
        ),
    ]
