# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_request_key',
            field=models.CharField(max_length=255),
        ),
    ]
