# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170712_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caller',
            old_name='registered_by',
            new_name='registered_device',
        ),
    ]
