# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170801_1709'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caller',
            name='caller_index',
        ),
        migrations.RenameField(
            model_name='caller',
            old_name='callerId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='caller',
            old_name='caller_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='deviceId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='devicePlatform',
            new_name='platform',
        ),
        migrations.AddIndex(
            model_name='caller',
            index=models.Index(fields=['country_code', 'number'], name='caller_index'),
        ),
    ]
