# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170704_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caller_categories',
            old_name='globalCategoryId',
            new_name='categoryId',
        ),
        migrations.AlterIndexTogether(
            name='caller_categories',
            index_together=set([('callerId', 'categoryId')]),
        ),
    ]
