# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170704_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
