# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170712_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_device',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
