# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170712_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caller_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ac_caller_category',
            },
        ),
        migrations.AlterField(
            model_name='caller',
            name='category',
            field=models.ManyToManyField(through='api.Caller_Category', to='api.Category'),
        ),
        migrations.AddField(
            model_name='caller_category',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Caller'),
        ),
        migrations.AddField(
            model_name='caller_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
