# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170715_0031'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caller_category',
            table='ac_caller_categories',
        ),
    ]
